FROM alpine:latest

RUN apk add --no-cache python3-dev && \
    pip3 install --upgrade pip

RUN mkdir /fantasy_pi_api
COPY . /fantasy_pi_api
RUN pip install -r /fantasy_pi_api/requirements.txt


EXPOSE 5555
